// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PupV1.Data;

#nullable disable

namespace PupV1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BreedtypeTrainer", b =>
                {
                    b.Property<int>("BreedId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("BreedId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("BreedtypeTrainer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PupV1.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BreederId")
                        .HasColumnType("int");

                    b.Property<string>("CellNUm")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KennelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BreederId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TrainerId")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PupV1.Models.BreedSpecialization", b =>
                {
                    b.Property<int>("BreederId")
                        .HasColumnType("int")
                        .HasColumnName("Breeder");

                    b.Property<int>("BreedId")
                        .HasColumnType("int")
                        .HasColumnName("Breedtype");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("BreederId", "BreedId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BreedId" }, "fk_BreedSpecialization_Specialization");

                    b.ToTable("breedspecialiation");
                });

            modelBuilder.Entity("PupV1.Models.Breeder", b =>
                {
                    b.Property<int>("BreederId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BreederID");

                    b.Property<string>("CellNum")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fname")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FName");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("KennelName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LicenceNum")
                        .HasColumnType("longtext");

                    b.Property<string>("Lname")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LName");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VerificationStatus")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("BreederId");

                    b.ToTable("breeder");
                });

            modelBuilder.Entity("PupV1.Models.Breedtype", b =>
                {
                    b.Property<int>("BreedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BreedId");

                    b.Property<string>("ActivityLevel")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("BreedName")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Grooming")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int?>("SaleCount")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("BreedId");

                    b.ToTable("breedtype");
                });

            modelBuilder.Entity("PupV1.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<string>("CellNum")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fname")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FName");

                    b.Property<string>("Lname")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LName");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int?>("PostCode")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("client");
                });

            modelBuilder.Entity("PupV1.Models.Litter", b =>
                {
                    b.Property<int>("LitterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LitterID");

                    b.Property<int>("AvailablePuppies")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("BreedId")
                        .HasColumnType("int")
                        .HasColumnName("BreedID");

                    b.Property<int?>("BreederId")
                        .HasColumnType("int")
                        .HasColumnName("BreederID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("NumPuppies")
                        .HasColumnType("int");

                    b.HasKey("LitterId");

                    b.HasIndex(new[] { "BreedId" }, "fk_Litter_Breed");

                    b.HasIndex(new[] { "BreederId" }, "fk_Litter_Breeder");

                    b.ToTable("litter");
                });

            modelBuilder.Entity("PupV1.Models.Parkrecommendation", b =>
                {
                    b.Property<int>("ParkCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int")
                        .HasColumnName("TrainerID");

                    b.HasKey("ParkCode");

                    b.HasIndex(new[] { "TrainerId" }, "fk_ParkRecommendation_Trainer");

                    b.ToTable("parkrecommendation");
                });

            modelBuilder.Entity("PupV1.Models.Puppy", b =>
                {
                    b.Property<int>("PuppyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PuppyID");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("BreederId")
                        .HasColumnType("int")
                        .HasColumnName("BreederID");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<string>("Colour")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int?>("LitterId")
                        .HasColumnType("int")
                        .HasColumnName("LitterID");

                    b.Property<string>("MicrochipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PuppyName")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("SaleStatus")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Size")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("TrainingStatus")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Vaccinated")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("VaccinationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PuppyId");

                    b.HasIndex("BreederId");

                    b.HasIndex(new[] { "ClientId" }, "fk_Puppy_Client");

                    b.HasIndex(new[] { "LitterId" }, "fk_Puppy_Litter");

                    b.ToTable("puppy");
                });

            modelBuilder.Entity("PupV1.Models.PuppyDetails", b =>
                {
                    b.Property<int>("PuppyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<int>("BreederId")
                        .HasColumnType("int");

                    b.Property<string>("BreederName")
                        .HasColumnType("longtext");

                    b.Property<string>("Colour")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.HasKey("PuppyId");

                    b.ToTable("PuppyDetailss");
                });

            modelBuilder.Entity("PupV1.Models.Puppyrequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    b.Property<int?>("BreederId")
                        .HasColumnType("int")
                        .HasColumnName("BreederID");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<DateTime?>("ExpDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PuppyId")
                        .HasColumnType("int")
                        .HasColumnName("PuppyID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("RequestId");

                    b.HasIndex("PuppyId");

                    b.HasIndex(new[] { "BreederId" }, "fk_PuppyRequest_Breeder");

                    b.HasIndex(new[] { "ClientId" }, "fk_PuppyRequest_Client");

                    b.ToTable("puppyrequest");
                });

            modelBuilder.Entity("PupV1.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    b.Property<int?>("BreederId")
                        .HasColumnType("int")
                        .HasColumnName("BreederID");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<double?>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int")
                        .HasColumnName("TrainerID");

                    b.HasKey("ReviewId");

                    b.HasIndex(new[] { "BreederId" }, "fk_Review_Breeder");

                    b.HasIndex(new[] { "ClientId" }, "fk_Review_Client");

                    b.HasIndex(new[] { "TrainerId" }, "fk_Review_Trainer");

                    b.ToTable("review");
                });

            modelBuilder.Entity("PupV1.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.Property<string>("SkillName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SkillId");

                    b.ToTable("skill");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            SkillName = "Animal Behaviour Knowledge"
                        },
                        new
                        {
                            SkillId = 2,
                            SkillName = "Training Techniques"
                        },
                        new
                        {
                            SkillId = 3,
                            SkillName = "Problem Behaviour Management"
                        },
                        new
                        {
                            SkillId = 4,
                            SkillName = "Breed_Specific Knowledge"
                        },
                        new
                        {
                            SkillId = 5,
                            SkillName = "Safety & First Aid for Dogs"
                        },
                        new
                        {
                            SkillId = 6,
                            SkillName = "Crate Training"
                        },
                        new
                        {
                            SkillId = 7,
                            SkillName = "House Training"
                        },
                        new
                        {
                            SkillId = 8,
                            SkillName = "Recall Training"
                        },
                        new
                        {
                            SkillId = 9,
                            SkillName = "Socialization Techniques"
                        },
                        new
                        {
                            SkillId = 10,
                            SkillName = "Impluse Control Training"
                        });
                });

            modelBuilder.Entity("PupV1.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrainerID");

                    b.Property<string>("CellNum")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fname")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("FName");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Lname")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("LName");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Suburb")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("VerificationStatus")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("TrainerId");

                    b.ToTable("trainer");
                });

            modelBuilder.Entity("PupV1.Models.Trainerskill", b =>
                {
                    b.Property<int>("TrainerId")
                        .HasColumnType("int")
                        .HasColumnName("TrainerID");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("TrainerId", "SkillId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "SkillId" }, "fk_TrainerSkill_Skill");

                    b.ToTable("trainerskill");
                });

            modelBuilder.Entity("PupV1.Models.TrainingProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DogBreed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DogName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Program")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgressNotes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("ProgressId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingProgresses");
                });

            modelBuilder.Entity("PupV1.Models.Trainingrequest", b =>
                {
                    b.Property<int>("TrequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRequestID");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("ClientID");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int")
                        .HasColumnName("TrainerID");

                    b.Property<string>("TrainingProgram")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TrequestId");

                    b.HasIndex(new[] { "ClientId" }, "fk_TrainingRequest_Client");

                    b.HasIndex(new[] { "TrainerId" }, "fk_TrainingRequest_Trainer");

                    b.ToTable("trainingrequest");
                });

            modelBuilder.Entity("BreedtypeTrainer", b =>
                {
                    b.HasOne("PupV1.Models.Breedtype", null)
                        .WithMany()
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PupV1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PupV1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PupV1.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PupV1.Models.ApplicationUser", b =>
                {
                    b.HasOne("PupV1.Models.Breeder", "Breeder")
                        .WithMany()
                        .HasForeignKey("BreederId");

                    b.HasOne("PupV1.Models.Client", "Client")
                        .WithOne()
                        .HasForeignKey("PupV1.Models.ApplicationUser", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PupV1.Models.Trainer", "Trainer")
                        .WithOne()
                        .HasForeignKey("PupV1.Models.ApplicationUser", "TrainerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Breeder");

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PupV1.Models.BreedSpecialization", b =>
                {
                    b.HasOne("PupV1.Models.Breedtype", "Breedtype")
                        .WithMany("BreedSpecializations")
                        .HasForeignKey("BreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.Breeder", "Breeder")
                        .WithMany("BreedSpecializations")
                        .HasForeignKey("BreederId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Breeder");

                    b.Navigation("Breedtype");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PupV1.Models.Litter", b =>
                {
                    b.HasOne("PupV1.Models.Breedtype", "BreedType")
                        .WithMany("Litters")
                        .HasForeignKey("BreedId");

                    b.HasOne("PupV1.Models.Breeder", "Breeder")
                        .WithMany("Litters")
                        .HasForeignKey("BreederId");

                    b.Navigation("BreedType");

                    b.Navigation("Breeder");
                });

            modelBuilder.Entity("PupV1.Models.Parkrecommendation", b =>
                {
                    b.HasOne("PupV1.Models.Trainer", "Trainer")
                        .WithMany("Parkrecommendations")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PupV1.Models.Puppy", b =>
                {
                    b.HasOne("PupV1.Models.Breeder", "Breeder")
                        .WithMany("Puppies")
                        .HasForeignKey("BreederId");

                    b.HasOne("PupV1.Models.Client", "Client")
                        .WithMany("Puppies")
                        .HasForeignKey("ClientId");

                    b.HasOne("PupV1.Models.Litter", "Litter")
                        .WithMany("Puppies")
                        .HasForeignKey("LitterId");

                    b.Navigation("Breeder");

                    b.Navigation("Client");

                    b.Navigation("Litter");
                });

            modelBuilder.Entity("PupV1.Models.Puppyrequest", b =>
                {
                    b.HasOne("PupV1.Models.Breeder", "Breeder")
                        .WithMany("Puppyrequests")
                        .HasForeignKey("BreederId");

                    b.HasOne("PupV1.Models.Client", "Client")
                        .WithMany("Puppyrequests")
                        .HasForeignKey("ClientId");

                    b.HasOne("PupV1.Models.Puppy", "Puppy")
                        .WithMany("Puppyrequests")
                        .HasForeignKey("PuppyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breeder");

                    b.Navigation("Client");

                    b.Navigation("Puppy");
                });

            modelBuilder.Entity("PupV1.Models.Review", b =>
                {
                    b.HasOne("PupV1.Models.Breeder", "Breeder")
                        .WithMany("Reviews")
                        .HasForeignKey("BreederId");

                    b.HasOne("PupV1.Models.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId");

                    b.HasOne("PupV1.Models.Trainer", "Trainer")
                        .WithMany("Reviews")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Breeder");

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PupV1.Models.Trainerskill", b =>
                {
                    b.HasOne("PupV1.Models.Skill", "Skill")
                        .WithMany("Trainerskills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.Trainer", "Trainer")
                        .WithMany("Trainerskills")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Skill");

                    b.Navigation("Trainer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PupV1.Models.TrainingProgress", b =>
                {
                    b.HasOne("PupV1.Models.Trainer", "Trainer")
                        .WithMany("TrainingProgresses")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PupV1.Models.Trainingrequest", b =>
                {
                    b.HasOne("PupV1.Models.Client", "Client")
                        .WithMany("Trainingrequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PupV1.Models.Trainer", "Trainer")
                        .WithMany("Trainingrequests")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PupV1.Models.Breeder", b =>
                {
                    b.Navigation("BreedSpecializations");

                    b.Navigation("Litters");

                    b.Navigation("Puppies");

                    b.Navigation("Puppyrequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PupV1.Models.Breedtype", b =>
                {
                    b.Navigation("BreedSpecializations");

                    b.Navigation("Litters");
                });

            modelBuilder.Entity("PupV1.Models.Client", b =>
                {
                    b.Navigation("Puppies");

                    b.Navigation("Puppyrequests");

                    b.Navigation("Reviews");

                    b.Navigation("Trainingrequests");
                });

            modelBuilder.Entity("PupV1.Models.Litter", b =>
                {
                    b.Navigation("Puppies");
                });

            modelBuilder.Entity("PupV1.Models.Puppy", b =>
                {
                    b.Navigation("Puppyrequests");
                });

            modelBuilder.Entity("PupV1.Models.Skill", b =>
                {
                    b.Navigation("Trainerskills");
                });

            modelBuilder.Entity("PupV1.Models.Trainer", b =>
                {
                    b.Navigation("Parkrecommendations");

                    b.Navigation("Reviews");

                    b.Navigation("Trainerskills");

                    b.Navigation("TrainingProgresses");

                    b.Navigation("Trainingrequests");
                });
#pragma warning restore 612, 618
        }
    }
}
